### ISSUE TITLE
Docker installation of MySQL 8 to Scaleway Server

### ISSUE THREAD

**Issue by bsemot** [EmakinaTR/makina-api#2]
Docker version 18.06.1-ce, build e68fc7a up and running on our Scaleway test server, There is already a MySQL server running at the same server, please don't touch it. Go for a fresh installation over docker.

**Comment by ilhan-mstf** [comment]
I created a docker image following this tutorial on my locale: https://dev.mysql.com/doc/mysql-installation-excerpt/8.0/en/docker-mysql-getting-started.html 

As a next step I am going to create sample a node app that connects to mysql and this app will also run on docker.

**Comment by ilhan-mstf** [comment]
I'm going to share my experiences about connecting a node app to mysql (both of them are running on docker containers)
- MySQL 8 uses different default authentication method and it is not supported by the [mysql npm module](https://www.npmjs.com/package/mysql). Therefore we need to update authentication method after image created. (There is another [npm module](https://www.npmjs.com/package/@mysql/xdevapi) but I am not sure that it is supported by the typeorm.)

Below configuration is worked on my linux laptop:

DB Dockerfile:
```
FROM mysql/mysql-server:latest

ENV MYSQL_ROOT_PASSWORD ABcd1234
ENV MYSQL_DATABASE product_app
ENV MYSQL_USER product_api
ENV MYSQL_PASSWORD ABcd1234

ADD setup.sql /docker-entrypoint-initdb.d

#EXPOSE 3306
```

setup.sql

`ALTER USER product_api IDENTIFIED WITH mysql_native_password BY 'ABcd1234';`

docker-compose.yml
```
version: '3.3'

services:
  db:
    build: ./db-service
    # If you want to access from command line uncomment below lines
    #ports:
    #  - "3306:3306"
    networks:
      - app-network
  product-service:
    build: ./product-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    networks:
      - app-network

networks:
  app-network:
```
`DATABASE_HOST` environment variable is required. I tried many configuration however, only this configuration worked out in order to connect two different docker container.

A sample folder structure could be like this:

```
- /microservice-app
  - docker-compose.yaml
  - /db-service
    - DockerFile
    - setup.sql
  - /api-service
    - DockerFile
    - ...
  - /website
    - Dockerfile
    - ...
```
